
version: "3.7"

services:

  relational_db:
    image: postgres:11-alpine
    container_name: ${RELATIONAL_DB_NAME}
    ports:
      - ${RELATIONAL_DB_PORT}:${RELATIONAL_DB_PORT}
    environment:
      - POSTGRES_USER=${RELATIONAL_DB_USERNAME}
      - POSTGRES_PASSWORD=${RELATIONAL_DB_PASSWORD}
    env_file:
      - .env
    command: ["-p", "${RELATIONAL_DB_PORT}"]
    networks:
      - flask_docker_network

networks:
  flask_docker_network:
    external:
      name: ${DOCKER_NETWORK}
